# Generated by Django 3.2.8 on 2021-12-01 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20211201_1310'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='article',
            table='Article',
        ),
        migrations.AlterModelTable(
            name='source',
            table='Source',
        ),
    ]
